# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
{
  "cli": {
    "version": ">= 3.19.0"
  },
  "build": {
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "env": {
        "EXPO_PUBLIC_API_URL": "https://api.ffideal.app"
      }
    },
    "production": {
      "distribution": "store",
      "android": {
        "buildType": "app-bundle"
      },
      "ios": {
        "workflow": "managed"
      },
      "env": {
        "EXPO_PUBLIC_API_URL": "https://api.ffideal.app"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
EXPO_PUBLIC_API_URL=https://api.ffideal.app
EAS_TOKEN=
EXPO_EMAIL=fulfilmentideal@gmail.com
ANDROID_PACKAGE=com.ffideal.app
IOS_BUNDLE=com.ffideal.app
# Files and folders to ignore in EAS builds
node_modules
.git
.gitignore
README.md
*.zip
*.env
*.log
.DS_Store
name: FFIdeal — Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g eas-cli expo-cli
          npm ci

      - name: Login to Expo
        env:
          EXPO_EMAIL: fulfilmentideal@gmail.com
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
        run: |
          eas whoami || eas login --non-interactive --username "$EXPO_EMAIL" --password "$EXPO_PASSWORD"

      - name: Build Android APK
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          eas build -p android --profile preview --non-interactive

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffideal-apk
          path: dist/*.apk
# 🚀 FFIdeal EAS CI Setup

Эта конфигурация предназначена для автоматической сборки APK через **Expo EAS** и **GitHub Actions**.

---

## 🔧 Подготовка

1. Создай аккаунт на [https://expo.dev/signup](https://expo.dev/signup)
   - Email: `fulfilmentideal@gmail.com`
   - Пароль: <твой пароль>

2. Сгенерируй EAS токен:
   [https://expo.dev/accounts/ffideal/settings/access-tokens](https://expo.dev/accounts/ffideal/settings/access-tokens)

3. Добавь секреты в GitHub:
   - `EAS_TOKEN` — токен из Expo
   - `EXPO_PASSWORD` — пароль от аккаунта Expo

4. Проверь, что структура проекта такая:

---

## 🧱 Запуск сборки

После каждого `push` в ветку `main` или при ручном запуске через вкладку **Actions**  
GitHub автоматически соберёт Android APK.

1. Перейди во вкладку **Actions** в репозитории GitHub.
2. Найди workflow **“FFIdeal — Build Android APK”**.
3. После завершения скачай готовый APK из раздела **Artifacts**.

---

## 🌍 Переменные окружения

| Название | Описание | Пример |
|-----------|-----------|--------|
| `EXPO_PUBLIC_API_URL` | Базовый URL API | `https://api.ffideal.app` |
| `EAS_TOKEN` | Expo Access Token | `eyJhbGciOi...` |
| `EXPO_EMAIL` | Expo аккаунт | `fulfilmentideal@gmail.com` |
| `ANDROID_PACKAGE` | Android package ID | `com.ffideal.app` |
| `IOS_BUNDLE` | iOS bundle ID | `com.ffideal.app` |

---

## 🧩 Советы
- Старайся не хранить `.env` в репозитории — только `.env.example`.
- Можно запускать сборку вручную в разделе **Actions → Run workflow**.
- Через Expo Dashboard можно отслеживать прогресс сборки.

---

🟢 После загрузки этих файлов и добавления секретов
GitHub Actions автоматически соберёт APK и выложит его как артефакт.
